### ISSUE TITLE
Finish adding celery support for competitions

### ISSUE THREAD

**Issue by bplower** [bplower/cssef#7]
I have very basic support for celery. Exception handling needs to be added. Changing competition start time doesn't remove the previously scheduled celery task.

**Comment by brahmlower** [comment]
The nature of this issue has changed some since splitting the core server from the web interface. I need to reimplement competition scheduling now.

**Comment by brahmlower** [comment]
This issue is very misleading. I'm just closing this. Competition scheduling is just a feature of the that one particular competition module, and will be handled when I fully focus on finishing it.
